export const PORTALS = [
  {
    name: "Bento",
    tags: ["訂餐"],
    href: "https://bento.winlab.tw",
    icon: "/bento.png",
    isCommon: true,
  },
  {
    name: "Reimburse",
    tags: ["金庫"],
    href: "https://reimburse.winlab.tw",
    icon: "/reimburse.png",
    isCommon: true,
  },
  {
    name: "Approve",
    tags: ["簽核"],
    href: "https://approve.winlab.tw",
    icon: "/approve.png",
    isCommon: true,
  },
  {
    name: "Leave",
    tags: ["請假"],
    href: "https://leave.winlab.tw",
    icon: "/leave.png",
    isCommon: true,
  },
  {
    name: "Nextcloud",
    tags: ["儲存", "Winfra"],
    href: "https://nextcloud.winfra.cs.nycu.edu.tw",
    icon: "/cloud.png",
    isCommon: false,
  },
  {
    name: "Wiki",
    tags: ["百科", "Winfra"],
    href: "https://wiki.winfra.cs.nycu.edu.tw",
    icon: "/wiki.png",
    isCommon: false,
  },
  {
    name: "GitLab",
    tags: ["Git", "Winfra"],
    href: "https://gitlab.winfra.cs.nycu.edu.tw",
    icon: "/git.png",
    isCommon: false,
  },
];
